language: node_js
node_js:
- 'node'

script:
  - npm i
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  skip-cleanup: true
  local-dir: public
  repo: Grishy/grishy.github.io
  target-branch: master
  on:
    branch: master
