baseURL = "https://grishy.ru/"
languageCode = "ru"
title = "Grishy"
theme = "grishy"
disableHugoGeneratorInject = true

[params]
    description = "Заметки на разные темы"

[Author]
    name  = "Sergey Grishin"
    email  = "mail@grishy.ru"
    github = "https://github.com/Grishy"
    vk = "https://vk.com/grishy"
    youtube = "https://www.youtube.com/channel/UCFZ-HfpBnMbiB8rCeijB80Q"
    telegram = "https://telegram.me/grishyru"

[[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Сокровища"
    url = "treasures"
    weight = 2
[[menu.main]]
    name = "Обо мне"
    url = "about"
    weight = 3
[[menu.main]]
    name = "Архив"
    url = "archive"
    weight = 4
